keys:
  - &primary age16qxll3wr9mtyad6yqu3338g65096auwp7szxdlurv6ph4s6ynp7sn052rv
    # to generate:
    # nix-shell -p ssh-to-age age
    # sudo ssh-to-age -private-key -i ~/.ssh/id_ed25519 -o keys.txt
    # age-keygen -y keys.txt
  - &hosts:
    - &judgement age1km6wqnpc3nyfww07ur80yq8hfzsshj8pqdella0q9k3cz2csh35qn382vz
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: common.yaml$
    key_groups:
    - age:
      - *primary
      - *judgement
  - path_regex: judgement.yaml$
    key_groups:
    - age:
      - *primary
      - *judgement
